--- Light mode palette: auto-generated by inverting the dark palette via HSLuv.
--- Override this file with a custom palette if you want manual control.

---@param opts mytheme.Config
return function(opts)
  local Util = require("mytheme.util")

  ---@type Palette
  local colors = vim.deepcopy(Util.mod("mytheme.colors.dark"))

  Util.invert(colors)
  colors.bg_dark = Util.blend(colors.bg, 0.9, colors.fg)
  colors.bg_darker = Util.blend(colors.bg_dark, 0.9, colors.fg)
  return colors
end
